CREATE DATABASE company_db;

DROP TABLE IF EXISTS Company;
CREATE TABLE Company (
  "id"   BIGINT UNIQUE  NULL DEFAULT NULL,
  "name" VARCHAR(50)    NULL DEFAULT NULL,
  "balance" DOUBLE PRECISION	 NULL DEFAULT 0

);


Drop TABLE IF EXISTS t_info;
CREATE TABLE t_info (
  "id"   BIGINT UNIQUE NULL DEFAULT NULL,
  "company" BIGINT NULL  DEFAULT NULL ,
  "action" VARCHAR(50)    NULL DEFAULT NULL,
  "value" DOUBLE PRECISION NULL DEFAULT NULL ,
  "balance" DOUBLE PRECISION NULL DEFAULT NULL ,
  "status" VARCHAR(50)    NULL DEFAULT NULL
);